CREATE TABLE "loan_applications" (
	"application_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"father_name" text NOT NULL,
	"mother_name" text,
	"dob" date NOT NULL,
	"gender" text NOT NULL,
	"mobile" text NOT NULL,
	"alternate_mobile" text,
	"email" text,
	"full_address" text NOT NULL,
	"district" text NOT NULL,
	"state" text NOT NULL,
	"pin_code" text NOT NULL,
	"pan_encrypted" text NOT NULL,
	"aadhaar_encrypted" text NOT NULL,
	"aadhaar_front_url" text NOT NULL,
	"aadhaar_back_url" text NOT NULL,
	"pan_card_url" text NOT NULL,
	"loan_amount" numeric(12, 2) NOT NULL,
	"interest_rate" numeric(8, 4) NOT NULL,
	"loan_start_date" date NOT NULL,
	"due_date" date NOT NULL,
	"loan_duration" text NOT NULL,
	"purpose_of_loan" text NOT NULL,
	"payment_method" text NOT NULL,
	"bank_name" text,
	"account_holder_name" text,
	"account_number" text,
	"ifsc_code" text,
	"upi_id" text,
	"emergency_contact_name" text NOT NULL,
	"emergency_contact_relationship" text NOT NULL,
	"emergency_contact_mobile" text NOT NULL,
	"guarantor_name" text,
	"guarantor_mobile" text,
	"guarantor_aadhaar_encrypted" text,
	"signature_url" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
