import * as React from "react";

interface LoanReminderEmailProps {
  borrowerName: string;
  principal: number;
  outstandingBalance: number;
  interestDue: number;
  penaltyAmount: number;
  dueDate: string;
}

export const LoanReminderEmail: React.FC<Readonly<LoanReminderEmailProps>> = ({
  borrowerName,
  principal,
  outstandingBalance,
  interestDue,
  penaltyAmount,
  dueDate,
}) => (
  <div style={{ fontFamily: "Arial, sans-serif", padding: "20px", color: "#333", maxWidth: "600px", margin: "0 auto", border: "1px solid #eee", borderRadius: "8px" }}>
    <h2 style={{ color: "#dc2626", borderBottom: "2px solid #dc2626", paddingBottom: "10px" }}>Finexa — Payment Reminder</h2>
    <p>Dear <strong>{borrowerName}</strong>,</p>
    <p>This is a reminder that your loan payment is due. Below are the current repayment details:</p>
    <table style={{ width: "100%", borderCollapse: "collapse", margin: "20px 0" }}>
      <tbody>
        <tr>
          <td style={{ padding: "10px", fontWeight: "bold", borderBottom: "1px solid #eee", width: "40%" }}>Principal Amount</td>
          <td style={{ padding: "10px", borderBottom: "1px solid #eee" }}>₹{principal.toLocaleString("en-IN")}</td>
        </tr>
        <tr>
          <td style={{ padding: "10px", fontWeight: "bold", borderBottom: "1px solid #eee" }}>Outstanding Balance</td>
          <td style={{ padding: "10px", borderBottom: "1px solid #eee", fontWeight: "bold" }}>₹{outstandingBalance.toLocaleString("en-IN")}</td>
        </tr>
        <tr>
          <td style={{ padding: "10px", fontWeight: "bold", borderBottom: "1px solid #eee" }}>Interest Owed</td>
          <td style={{ padding: "10px", borderBottom: "1px solid #eee" }}>₹{interestDue.toLocaleString("en-IN")}</td>
        </tr>
        <tr>
          <td style={{ padding: "10px", fontWeight: "bold", borderBottom: "1px solid #eee" }}>Late Penalty Applied</td>
          <td style={{ padding: "10px", borderBottom: "1px solid #eee", color: penaltyAmount > 0 ? "#dc2626" : "#333" }}>₹{penaltyAmount.toLocaleString("en-IN")}</td>
        </tr>
        <tr>
          <td style={{ padding: "10px", fontWeight: "bold", borderBottom: "1px solid #eee" }}>Due Date</td>
          <td style={{ padding: "10px", borderBottom: "1px solid #eee", color: "#dc2626", fontWeight: "bold" }}>{dueDate}</td>
        </tr>
      </tbody>
    </table>
    <p>Please arrange for the repayment of the outstanding balance. If you have already made a payment, please share the receipt details with the Finexa Credit Control & Legal Division so it can be verified and updated in the system.</p>
    <p style={{ fontSize: "12px", color: "#666", marginTop: "30px", borderTop: "1px solid #eee", paddingTop: "15px", lineHeight: "1.4" }}>
      This email is automatically generated by Finexa on behalf of the Finexa Credit Control & Legal Division. Finexa complies with the Digital Personal Data Protection (DPDP) Act, 2023 (India).
    </p>
  </div>
);
