import * as React from "react";

interface LoanCreatedEmailProps {
  borrowerName: string;
  principal: number;
  monthlyInterest: number;
  interestRate: number;
  dateGiven: string;
  dueDate: string;
}

export const LoanCreatedEmail: React.FC<Readonly<LoanCreatedEmailProps>> = ({
  borrowerName,
  principal,
  monthlyInterest,
  interestRate,
  dateGiven,
  dueDate,
}) => (
  <div style={{ fontFamily: "Arial, sans-serif", padding: "20px", color: "#333", maxWidth: "600px", margin: "0 auto", border: "1px solid #eee", borderRadius: "8px" }}>
    <h2 style={{ color: "#2563eb", borderBottom: "2px solid #2563eb", paddingBottom: "10px" }}>Finexa — Loan Confirmation</h2>
    <p>Dear <strong>{borrowerName}</strong>,</p>
    <p>This email is to notify you that your loan has been officially recorded in the Finexa management platform. Please find the details of the agreement below:</p>
    <table style={{ width: "100%", borderCollapse: "collapse", margin: "20px 0" }}>
      <tbody>
        <tr>
          <td style={{ padding: "10px", fontWeight: "bold", borderBottom: "1px solid #eee", width: "40%" }}>Principal Amount</td>
          <td style={{ padding: "10px", borderBottom: "1px solid #eee" }}>₹{principal.toLocaleString("en-IN")}</td>
        </tr>
        <tr>
          <td style={{ padding: "10px", fontWeight: "bold", borderBottom: "1px solid #eee" }}>Interest Rate</td>
          <td style={{ padding: "10px", borderBottom: "1px solid #eee" }}>₹{interestRate} per ₹1,000 / month</td>
        </tr>
        <tr>
          <td style={{ padding: "10px", fontWeight: "bold", borderBottom: "1px solid #eee" }}>Monthly Interest Owed</td>
          <td style={{ padding: "10px", borderBottom: "1px solid #eee" }}>₹{monthlyInterest.toLocaleString("en-IN")}</td>
        </tr>
        <tr>
          <td style={{ padding: "10px", fontWeight: "bold", borderBottom: "1px solid #eee" }}>Date Issued</td>
          <td style={{ padding: "10px", borderBottom: "1px solid #eee" }}>{dateGiven}</td>
        </tr>
        <tr>
          <td style={{ padding: "10px", fontWeight: "bold", borderBottom: "1px solid #eee" }}>Repayment Due Date</td>
          <td style={{ padding: "10px", borderBottom: "1px solid #eee", color: "#dc2626", fontWeight: "bold" }}>{dueDate}</td>
        </tr>
      </tbody>
    </table>
    <p>Please note that if the loan is not repaid by the due date, it will automatically extend by one further period, and another period's interest will be applied to the original principal in accordance with the agreement.</p>
    <p style={{ fontSize: "12px", color: "#666", marginTop: "30px", borderTop: "1px solid #eee", paddingTop: "15px", lineHeight: "1.4" }}>
      This email is automatically generated by Finexa on behalf of the Finexa Credit Control & Legal Division. Finexa complies with the Digital Personal Data Protection (DPDP) Act, 2023 (India) regarding the secure processing of personal identifiers.
    </p>
  </div>
);
